services:
  mongo-manager-cli:
    image: cicarulez/mongo-manager-cli:latest
    container_name: mongo-manager-cli
    tty: true
    stdin_open: true
    environment:
      - MONGO_URL=mongodb://mongo:<password>@mongo-secure:27017/db_name?authSource=admin
      - DATA_COLLECTION_NAME=data
      - USER_COLLECTION_NAME=users
      - ENABLE_EXCEL_EXPORT=true
      - CONVERTER_API_URL=http://excel-json-converter:3000/api/files/convertJsonToExcel
    volumes:
      - ./exports:/usr/app/exports
    networks:
      - shared-network
      - internal-network
    depends_on:
      - excel-json-converter

  excel-json-converter:
    image: cicarulez/excel-json-converter:latest
    container_name: excel-json-converter
    environment:
      - SWAGGER=true
      - PORT=3000
    restart: unless-stopped
    networks:
      - shared-network
      - internal-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  exports:

networks:
  shared-network:
    external: true
  internal-network:
    driver: bridge
