services:
  mongo_manager_app:
    image: mongo_manager_image
    container_name: mongo_manager_app
    tty: true
    stdin_open: true
    environment:
      - MONGO_URL=mongodb://mongo:<password>@mongo-secure:27017/db_name?authSource=admin
      - DATA_COLLECTION_NAME=data
      - USER_COLLECTION_NAME=users
    volumes:
      - ./exports:/usr/exports
    networks:
      - shared-network

volumes:
  exports:

networks:
  shared-network:
    external: true
