services:
  app:
    image: mongo_manager_image
    container_name: mongo_manager_app
    environment:
      - MONGO_URL=${MONGO_URL}
      - DATA_COLLECTION_NAME=${DATA_COLLECTION_NAME}
      - USER_COLLECTION_NAME=${USER_COLLECTION_NAME}
    stdin_open: true
    tty: true