services:
  mongo_manager_app:
    image: mongo_manager_image
    container_name: mongo_manager_app
    tty: true
    stdin_open: true
    env_file: ./envs/.env
    volumes:
      - ./exports:/usr/exports
    networks:
      - shared-network

volumes:
  exports:

networks:
  shared-network:
    external: true