name: Docker Image CI

on:
  push:
    tags:
      - "*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app and build Docker image
        run: docker build . --file Dockerfile --tag cicarulez/mongo-manager:${{ github.ref_name }}

      - name: Tag Docker image as latest
        run: docker tag cicarulez/mongo-manager:${{ github.ref_name }} cicarulez/mongo-manager:latest

      - name: Publish Docker images to Docker Hub
        run: |
          docker login -u cicarulez -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push cicarulez/mongo-manager:${{ github.ref_name }}
          docker push cicarulez/mongo-manager:latest
